#:schema node_modules/wrangler/config-schema.json
name = "image-analysis-consumer"
main = "src/index.ts"
compatibility_date = "2024-08-15"

[[queues.consumers]]
queue = "image-analysis"

[ai]
binding = "AI"

[[d1_databases]]
binding = "DB"
database_name = "image-analysis"
database_id = "5d6b2d05-b857-41f1-903c-39dc3de88dd2"

[[r2_buckets]]
binding = 'IMAGE_APP_UPLOADS'
bucket_name = 'image-app-uploads'
