#:schema node_modules/wrangler/config-schema.json
name = "weather-app"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[kv_namespaces]]
binding = "WEATHER_CACHE"
id = "335ee201b19e41bbad3fca786e15e0d3"

[[env.preview.kv_namespaces]]
binding = "WEATHER_CACHE"
id = "335ee201b19e41bbad3fca786e15e0d3"

[[env.production.kv_namespaces]]
binding = "WEATHER_CACHE"
id = "2b99b17f3641482a86a33d1287afc0f4"
