#:schema node_modules/wrangler/config-schema.json
name = "image-app"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[r2_buckets]]
binding = "IMAGE_APP_UPLOADS"
bucket_name = "image-app-uploads-preview"

[[env.preview.r2_buckets]]
binding = "IMAGE_APP_UPLOADS"
bucket_name = "image-app-uploads-preview"

[[env.production.r2_buckets]]
binding = "IMAGE_APP_UPLOADS"
bucket_name = "image-app-uploads"
