#:schema node_modules/wrangler/config-schema.json
name = "photo-service"
main = "src/index.ts"
compatibility_date = "2024-08-15"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB" # i.e. available in your Worker on env.DB
database_name = "photo-service"
database_id = "53295159-95fd-4e30-b1d5-07d51f461d69"
